# Creating Tensor


### We will create a helper function, describe(x), that will summarize various properties of a tensor x
- Type of the tensor
- The dimensions of the tensor
- The contents of the tensor

In [1]:
def describe(x):
    print("Type: {}".format(x.type()))
    print("Shape/size: {}".format(x.shape))
    print("Values: \n{}".format(x))#


### Creating a Tensor in Pytorch Using tensor.Tensor

In [2]:
import torch
describe(torch.Tensor(4,5))

Type: torch.FloatTensor
Shape/size: torch.Size([4, 5])
Values: 
tensor([[4.6243e-44, 0.0000e+00, 3.9236e-44, 0.0000e+00, 1.5540e+07],
        [4.5821e-41, 4.6534e+33, 1.7743e+28, 2.0535e-19, 6.8609e+22],
        [1.4868e-41, 0.0000e+00, 6.8664e-44, 0.0000e+00, 6.3058e-44],
        [0.0000e+00, 1.5293e+07, 4.5821e-41, 6.8664e-44, 0.0000e+00]])


### Creating a Randomly Initialized Tensor

In [10]:
import torch
describe(torch.rand(4,5)) #Uniform Distribution Between 0 & 1
describe(torch.randn(4,5)) #Following the Normal Distribution 

Type: torch.FloatTensor
Shape/size: torch.Size([4, 5])
Values: 
tensor([[0.3811, 0.2914, 0.8307, 0.8306, 0.2709],
        [0.8118, 0.5135, 0.6557, 0.8479, 0.7547],
        [0.0400, 0.0985, 0.6936, 0.6848, 0.6913],
        [0.4526, 0.6681, 0.8376, 0.3412, 0.7678]])
Type: torch.FloatTensor
Shape/size: torch.Size([4, 5])
Values: 
tensor([[-0.7960, -0.0809, -0.8367, -0.0783,  1.2995],
        [ 1.1490, -0.6494, -1.1974,  0.1161,  0.8806],
        [ 1.2214, -2.3070,  2.0963, -0.3905, -1.0725],
        [-0.0853, -0.1430, -0.1704,  1.1637,  0.8990]])


### Creating Tensor filled with Scalar

In [3]:
import torch
describe(torch.zeros(3,3)) #Tensor of all zeros
describe(torch.ones(3,3))  #Tensor of all ones
x = torch.ones(3,3)
x.fill_(5)           #Fill 
describe(x)


Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


### Creating and initializing a tensor from lists

In [4]:
x = torch.Tensor([[1,2,3],[4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Creating and initializing a tensor from numpy

In [6]:
import numpy as np
data = np.random.rand(4,5)
describe(torch.from_numpy(data))

Type: torch.DoubleTensor
Shape/size: torch.Size([4, 5])
Values: 
tensor([[0.3505, 0.6490, 0.9826, 0.6645, 0.4831],
        [0.1990, 0.5437, 0.8746, 0.4413, 0.2715],
        [0.7130, 0.3894, 0.0868, 0.4394, 0.6573],
        [0.2858, 0.9084, 0.4769, 0.1668, 0.4897]], dtype=torch.float64)


We notice that the type of the tensor is DoubleTensor instead of the default FloatTensor becsause the data type of the NumPy random matrix is a float64

### Tensor Types and Sizes


Each tensor has an associated type and size. The default tensor type when you use the torch.Tensor constructor is torch.FloatTensor. We can convert a tensor to a different type (float, long, double, etc.) by specifying it at initialization or later using one of the typecasting methods. 
There are two ways to specify the initialization type: either by directly calling the constructor of a specific tensor type, such as FloatTensor or LongTensor, or using a special method, torch.tensor(), and providing the dtype.

In [14]:
x = torch.Tensor([[1,2,3],[4,5,6]])
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [15]:
x = x.long()
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [18]:
x = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.int64)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [19]:
x = x.float()
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Tensor Operations

In [20]:
x = torch.randn((3,3))
describe(x)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[-1.1340, -0.5330,  1.1113],
        [-3.2175,  0.6783,  1.2445],
        [-1.7195, -0.1501,  0.5245]])


In [22]:
y = torch.add(x,x)
describe(y)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[-2.2680, -1.0660,  2.2225],
        [-6.4351,  1.3565,  2.4890],
        [-3.4389, -0.3001,  1.0491]])


In [25]:
x = torch.arange(6)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [28]:
x = x.view(2,3)
describe(x)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [29]:
describe(torch.sum(x,dim=0))


Type: torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [30]:
describe(torch.sum(x,dim =1))

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [31]:
y = torch.transpose(x,0,1)
describe(y)

Type: torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


### Indexing Slicing and Joining

In [37]:
tensor_new = torch.arange(6).view(2,3)
describe(tensor_new)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [39]:
describe(tensor_new[:1,:2])

Type: torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])


In [40]:
describe(tensor_new[0,1])


Type: torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


### Complex indexing: noncontiguous indexing of a tensor

In [41]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(tensor_new, dim=1, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


In [43]:
indices = torch.LongTensor([0, 0])
describe(torch.index_select(tensor_new, dim=0, index=indices))

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [0, 1, 2]])


In [45]:
row_indices = torch.arange(2).long()
print(row_indices)

tensor([0, 1])


In [46]:
col_indices = torch.LongTensor([0, 1])
print(col_indices)



tensor([0, 1])


In [47]:
describe(tensor_new[row_indices, col_indices])

Type: torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


### Concatenating Tensors

In [48]:
x1 = torch.arange(6).view(2,3)
describe(x1)

Type: torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [53]:
concat_tensor = torch.cat([x1,x1],dim=0)
describe(concat_tensor)

Type: torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [54]:
concat_tensor = torch.cat([x1,x1],dim=1)
describe(concat_tensor)

Type: torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [64]:

matrix1 = torch.arange(6).view(2,3).float()
describe(matrix1)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 1., 2.],
        [3., 4., 5.]])


In [65]:
matrix2 = torch.ones(3,2)

In [66]:
describe(matrix2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [67]:
matrix2[:,1] = matrix2[:,1]+1
describe(matrix2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [68]:
describe(torch.mm(matrix1,matrix2))

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


### Tensor and Computational Graphs

PyTorch tensor class encapsulates the data (the tensor itself) and a range of operations, such as algebraic operations, indexing, and reshaping operations. When the requires_grad Boolean flag is set to True on a tensor, bookkeeping operations are enabled that can track the gradient at the tensor as well as the gradient function, both of which are needed to facilitate the gradient-based learning.

#### Creating Tensors for Gradient BookKeeping

In [71]:
import torch
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [72]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [73]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type: torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
False


When you create a tensor with requires_grad=True, you are requiring PyTorch to manage bookkeeping information that computes gradients. First, PyTorch will keep track of the values of the forward pass. Then, at the end of the computations, a single scalar is used to compute a backward pass. The backward pass is initiated by using the backward() method on a tensor resulting from the evaluation of a loss function. The backward pass computes a gradient value for a tensor object that participated in the forward pass.

In general, the gradient is a value that represents the slope of a function output with respect to the function input. In the computational graph setting, gradients exist for each parameter in the model and can be thought of as the parameter’s contribution to the error signal. In PyTorch, you can access the gradients for the nodes in the computational graph by using the .grad member variable. Optimizers use the .grad variable to update the values of the parameters.

#### Squeeze Method - Returns a tensor with all the dimensions of input of size 1 removed

In [122]:
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())

torch.Size([2, 1, 2, 1, 2])


In [123]:
y = torch.squeeze(x)
print(y.size())

torch.Size([2, 2, 2])


#### Add 1 Extra Dimension Here using the Unsqueeze Method

In [124]:
y = y.unsqueeze(0)

In [126]:
y.size()


torch.Size([1, 2, 2, 2])

#### Create a random tensor of shape 5x3 in the interval [3, 7)

3 + torch.rand(5, 3) * (7 - 3)

#### Create a tensor with values from a normal distribution (mean=0, std=1).

In [132]:
a = torch.rand(3,3)
describe(a)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 3])
Values: 
tensor([[0.3876, 0.8188, 0.3421],
        [0.8082, 0.1886, 0.6601],
        [0.4997, 0.7893, 0.3232]])


#### Retrieve the indexes of all the nonzero elements in the tensor torch.Tensor([1, 1, 1, 0, 1]).

In [133]:
mytensor = torch.Tensor([1,1,1,0,1])
describe(mytensor)

Type: torch.FloatTensor
Shape/size: torch.Size([5])
Values: 
tensor([1., 1., 1., 0., 1.])


In [134]:
print(torch.nonzero(mytensor))

tensor([[0],
        [1],
        [2],
        [4]])


#### Create a random tensor of size (3,1) and then horizontally stack four copies together.

In [136]:
y1 = torch.rand(3,1)
describe(y1)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 1])
Values: 
tensor([[0.1206],
        [0.4994],
        [0.0932]])


In [149]:
y2 = torch.cat([y1]*4,dim = 1)
describe(y2)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[0.1206, 0.1206, 0.1206, 0.1206],
        [0.4994, 0.4994, 0.4994, 0.4994],
        [0.0932, 0.0932, 0.0932, 0.0932]])


In [148]:
y3 = y1.expand(3,4)
describe(y3)

Type: torch.FloatTensor
Shape/size: torch.Size([3, 4])
Values: 
tensor([[0.1206, 0.1206, 0.1206, 0.1206],
        [0.4994, 0.4994, 0.4994, 0.4994],
        [0.0932, 0.0932, 0.0932, 0.0932]])
